version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: moyenga
    restart: unless-stopped
    environment:
      POSTGRES_USER: nassirou
      POSTGRES_PASSWORD: nassirou
      POSTGRES_DB: moyenga_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moyenga -d moyenga_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: moyenga-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moyenga.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
